[functions.biomedical-nlp]
verify_jwt = false

[functions.extract-medical-entities]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = false

[functions.generate-suggestions]
verify_jwt = false

[functions.get-secret]
verify_jwt = false

[functions.process-case-study]
verify_jwt = false