// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmlpzjtnmxwojejnugej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtbHB6anRubXh3b2plam51Z2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxMTE5NjQsImV4cCI6MjA1MDY4Nzk2NH0.7b4XSxOiVYSxICod_bYqjBKeNLjn_QcLoq-E9Yolk4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);